[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/']
ffi = true #should be false outside of this tutorial. Helps with the DevOpsTools
fs_permissions = [{access = "read", path = "./images"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
